version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: hansel_backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: hansel_frontend
    ports:
      - "3001:3000"
    # env_file:
    #   - ./frontend/.env
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:15
    container_name: hansel_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 200500123
      POSTGRES_DB: hansel_y_gretel
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
